SET FOREIGN_KEY_CHECKS = 0;

-- EXISTING TABLES REMOVAL
DROP TABLE IF EXISTS `order_products`;
DROP TABLE IF EXISTS `category_product`;
DROP TABLE IF EXISTS `products`;
DROP TABLE IF EXISTS `powers`;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS `categories`;

CREATE TABLE `products`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(180) NOT NULL,
    `short_description` TEXT NOT NULL COMMENT 'max 300 caratteri',
    `marketing_description` TEXT NOT NULL COMMENT 'max 800',
    `price_full` DECIMAL(10, 2) NOT NULL,
    `slug` VARCHAR(180) NOT NULL COMMENT 'generated by name',
    `ingredients` TEXT NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL,
    `power_id` BIGINT UNSIGNED NOT NULL,
    `image_main_url` TEXT NOT NULL,
    `image_lifestyle` TEXT NOT NULL,
    `image_ksp` TEXT NOT NULL
);
ALTER TABLE
    `products` ADD UNIQUE `products_slug_unique`(`slug`);
CREATE TABLE `categories`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `slug` VARCHAR(100) NOT NULL
);
ALTER TABLE
    `categories` ADD UNIQUE `categories_slug_unique`(`slug`);
CREATE TABLE `category_product`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `category_id` BIGINT UNSIGNED NOT NULL,
    `product_id` BIGINT UNSIGNED NOT NULL
);
ALTER TABLE
    `category_product` ADD INDEX `category_product_category_id_product_id_index`(`category_id`, `product_id`);
CREATE TABLE `orders`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `guest_email` VARCHAR(255) NOT NULL,
    `total_amount` DECIMAL(10, 2) NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `guest_name` VARCHAR(200) NOT NULL,
    `guest_surname` VARCHAR(200) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `house_number` VARCHAR(8) NOT NULL,
    `postal_code` VARCHAR(12) NOT NULL,
    `city` VARCHAR(100) NOT NULL,
    `country` VARCHAR(100) NOT NULL,
    `phone_number` VARCHAR(20) NOT NULL
);
CREATE TABLE `order_products`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `order_id` BIGINT UNSIGNED NOT NULL,
    `product_id` BIGINT UNSIGNED NOT NULL,
    `quantity` SMALLINT UNSIGNED NOT NULL,
    `price_at_purchase` DECIMAL(10, 2) NOT NULL
);
ALTER TABLE
    `order_products` ADD INDEX `order_products_order_id_product_id_index`(`order_id`, `product_id`);
CREATE TABLE `powers`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `power_type` VARCHAR(255) NOT NULL
);
ALTER TABLE
    `order_products` ADD CONSTRAINT `order_products_product_id_foreign` FOREIGN KEY(`product_id`) REFERENCES `products`(`id`);
ALTER TABLE
    `products` ADD CONSTRAINT `products_power_id_foreign` FOREIGN KEY(`power_id`) REFERENCES `powers`(`id`);
ALTER TABLE
    `category_product` ADD CONSTRAINT `category_product_product_id_foreign` FOREIGN KEY(`product_id`) REFERENCES `products`(`id`);
ALTER TABLE
    `order_products` ADD CONSTRAINT `order_products_order_id_foreign`
    FOREIGN KEY(`order_id`) REFERENCES `orders`(`id`);
ALTER TABLE
    `category_product` ADD CONSTRAINT `category_product_category_id_foreign` FOREIGN KEY(`category_id`) REFERENCES `categories`(`id`);